/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;
import Util.PadraoFormulario;

/**
 *
 * @author diego
 */
public class MDI extends javax.swing.JFrame {

    PadraoFormulario form = new PadraoFormulario();
    
    public MDI() {
        initComponents();
        iniciarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktop = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        Administracao = new javax.swing.JMenu();
        Mn_Funcionario = new javax.swing.JMenu();
        Mn_C_Funcio = new javax.swing.JMenuItem();
        Cliente = new javax.swing.JMenu();
        Estoque = new javax.swing.JMenu();
        MnC_Produt = new javax.swing.JMenu();
        C_Produt = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MnC_Deposito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDesktop.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlDesktopLayout = new javax.swing.GroupLayout(pnlDesktop);
        pnlDesktop.setLayout(pnlDesktopLayout);
        pnlDesktopLayout.setHorizontalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        pnlDesktopLayout.setVerticalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        Administracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/documento-50.png"))); // NOI18N
        Administracao.setText("Administração");

        Mn_Funcionario.setText("Funcionário");

        Mn_C_Funcio.setText("Cadastro de Funcionário");
        Mn_C_Funcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_C_FuncioActionPerformed(evt);
            }
        });
        Mn_Funcionario.add(Mn_C_Funcio);

        Administracao.add(Mn_Funcionario);

        Menu.add(Administracao);

        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/contatos-50.png"))); // NOI18N
        Cliente.setText("Cliente");
        Menu.add(Cliente);

        Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mais-50.png"))); // NOI18N
        Estoque.setText("Estoque");

        MnC_Produt.setText("Produto");
        MnC_Produt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnC_ProdutActionPerformed(evt);
            }
        });

        C_Produt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        C_Produt.setText("Cadastro de Produto");
        C_Produt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ProdutActionPerformed(evt);
            }
        });
        MnC_Produt.add(C_Produt);

        Estoque.add(MnC_Produt);

        jMenu1.setText("Estoque");

        MnC_Deposito.setText("Cadastro de Deposito");
        MnC_Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnC_DepositoActionPerformed(evt);
            }
        });
        jMenu1.add(MnC_Deposito);

        Estoque.add(jMenu1);

        Menu.add(Estoque);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop)
        );

        setSize(new java.awt.Dimension(914, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnC_ProdutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnC_ProdutActionPerformed

    }//GEN-LAST:event_MnC_ProdutActionPerformed

    private void C_ProdutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ProdutActionPerformed
        form.abrirFormulario(new C_Produt(), pnlDesktop);
    }//GEN-LAST:event_C_ProdutActionPerformed

    private void MnC_DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnC_DepositoActionPerformed
        form.abrirFormulario(new C_Deposito(), pnlDesktop);
    }//GEN-LAST:event_MnC_DepositoActionPerformed

    private void Mn_C_FuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_C_FuncioActionPerformed
        form.abrirFormulario(new C_Funcio(), pnlDesktop);
    }//GEN-LAST:event_Mn_C_FuncioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracao;
    private javax.swing.JMenuItem C_Produt;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MnC_Deposito;
    private javax.swing.JMenu MnC_Produt;
    private javax.swing.JMenuItem Mn_C_Funcio;
    private javax.swing.JMenu Mn_Funcionario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JDesktopPane pnlDesktop;
    // End of variables declaration//GEN-END:variables
    
    private void iniciarTela() {       
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

}
